version: '3.8'

services:
  auth:
    container_name: auth-service
    build:
      context: ./apps/auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://host.docker.internal:27017/you-app-db
      - JWT_SECRET=mySuperSecretKey
      - JWT_EXPIRESIN=3h
    depends_on:
      - mongodb

  user:
    container_name: user-service
    build:
      context: ..
      dockerfile: ./user/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://host.docker.internal:27017/you-app-db
      - JWT_SECRET=mySuperSecretKey
      - JWT_EXPIRESIN=3h
    depends_on:
      - mongodb

  chat:
    container_name: chat-service
    build:
      context: ..
      dockerfile: ./chat/Dockerfile
    ports:
      - "3003:3004"
    environment:
      - PORT=3004
      - MONGODB_URI=mongodb://host.docker.internal:27017/you-app-db
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - JWT_SECRET=mySuperSecretKey
      - JWT_EXPIRESIN=3h
    depends_on:
      - rabbitmq
      - mongodb

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: