services:
  app:
    container_name: you-app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/you-app-db
      - JWT_SECRET=mySuperSecretKey
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo_data: {}